version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project/benchmark-ci-tools
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir -p ~/project/benchmark-ci-tools/artifacts
            echo "my artifact file" > ~/project/benchmark-ci-tools/artifacts/art-1
            echo "my artifact files in a dir" > ~/project/benchmark-ci-tools/artifacts/art-2
            ls -la ~/project/benchmark-ci-tools/artifacts  # Lista os arquivos criados

      - store_artifacts:
          path: ~/project/benchmark-ci-tools/artifacts
          destination: artifacts-directory

      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

workflows:
  build-and-test:
    jobs:
      - test-java
