version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: /benchmark-ci-tools
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /benchmark-ci-tools/art-1;
            mkdir /benchmark-ci-tools/artifacts;
            echo "my artifact files in a dir" > /benchmark-ci-tools/artifacts/art-2;

      - store_artifacts:
          path: /benchmark-ci-tools/art-1
          destination: artifact-file

      - store_artifacts:
          path: /benchmark-ci-tools/artifacts

workflows:
  build-and-test:
    jobs:
      - test-java
