version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project/benchmark-ci-tools
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command:
workflows:
  build-and-test:
    jobs:
      - test-java


