version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project/benchmark-ci-tools
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Start Timer
          command:
          echo "Deploy started at: $(date)"
            - run:
                name: Deploy Application
                command: # Insira seu comando de deploy aqui (ex: ./deploy.sh)
            - run:
                name: End Timer
                command:
                  echo "Deploy finished at: $(date)"
            - run:
                name: Calculate Duration
                command: |
                  START=$(date +%s)
                  # Insira seu comando de deploy aqui
                  END=$(date +%s)
                  DIFF=$(( END - START ))
                  echo "Deploy duration: ${DIFF} seconds"
workflows:
  build-and-test:
    jobs:
      - test-java


